### PR TITLE
Ensure `FileSystemException` is always thrown when `File.open{Read/ReadWrite/Write}` points to a directory

### LINKED ISSUE #215: Open failures attributed to `EISDIR` should throw `FileSystemException`
Several places where `FileNotFoundException` is being thrown when `openRead`, `openReadWrite` or `openWrite` fail due to the `File` pointing to a directory. This should always be a `FileSystemException` with a reason containing the string `Is a directory`. For `FsUnix`, `FsJsNode`, and `FsJvmAndroid` if the errno is `EISDIR`, that will also be included as the prefix, but `Is a directory` should be the keyword to land on.

### PR DESCRIPTION
**Pull request by 05nelsonm**
Closes #215

### CODE REVIEW

File: library/file/src/jvmTestShared/kotlin/io/matthewnelson/kmp/file/FileStreamWriteJvmSharedTest.kt [hunk 1]
```diff
@@ -92,7 +92,7 @@ abstract class FileStreamWriteJvmSharedTest: FileStreamWriteSharedTest() {
                 s = tmp.testOpen(excl = OpenExcl.MustExist, appending = true)
                 fail("open should have failed due to missing write permissions...")
             } catch (e: AccessDeniedException) {
-                assertEquals(true, e.message?.contains("permission denied", ignoreCase = true))
+                assertEquals(true, e.message?.contains("denied"), e.message)
```
Comment (05nelsonm) [inline library/file/src/jvmTestShared/kotlin/io/matthewnelson/kmp/file/FileStreamWriteJvmSharedTest.kt]: Check `e.file == tmp`
